### ISSUE TITLE
Make highlighting not bad

### ISSUE THREAD

**Issue by JoelO** [CheeseLord/wat#38]
Highlighting is awful.  We should fix it.

Ideas
1. Create an interface for highlighting (ease of use elsewhere).
2. No path highlighting for ranged actions.
3. Keep path highlighting for movement.

Steps
1. Refactor code

**Comment by kronmillerg** [comment]
Some specific complaints:

* `hoverHighlightObj` should take an action, not just the target
* `hoverHighlightObj` hardcodes the fact that all highlighted actions are move+target
* The `Highlight` enum in consts.js
  * Currently this needs to be a bunch of integers so we can apply multiple highlights to an object and have certain ones take precedence over others. Can we scrap that approach? Seems like there are only a couple sources of highlights (auto actions, highlights), so we ought to be able to specify one highlight color for each source and then choose the overall highlight color based on which source takes precedence.
  * In that case we could probably have the named constants refer directly to the colors, and delete the switch statements in `GridObject._redraw` (world_component.js)
* Also, time to finally eliminate `HL_STRAT`. Maintaining two different highlighting schemes at once is a burden on the code.

**Comment by kronmillerg** [comment]
1, 3, and 4 are done.

2 needs to have a case for actually highlighting an action that isn't move+target. So we can't really do it until we're actually highlighting ranged attacks (or something else).

**Comment by kronmillerg** [comment]
#2 is also solved. There are still some things to fix w/r/t highlighting, but I think at this point it makes more sense to file separate issues for specific complaints, rather than having a catchall for "things are bad".
